In [30]:
import pandas as pd; 

#caminhoWindows = "C:/Users/NSOUZA/OneDrive - Daimler Truck/04-CURSOS/23-Analise_dadosRPA/Vendas_Jan.xlsx"
caminhoLinux = "/home/nsouza/Público/Cursos/analisedadosRPA/Vendas_Jan.xlsx"
vendas_DataFrame = pd.read_excel(caminhoLinux)

display(vendas_DataFrame)

            Vendedor                        Produto Data Venda  Total Vendas
0   Leonardo Almeida                 Tênis Feminino 2023-01-01        719.92
1     Eliane Moreira          Calça Feminina Jogger 2023-01-02        139.98
2    Nicolas Pereira               Camisa Masculina 2023-01-03        306.80
3     Amanda Martins              Bermuda Masculino 2023-01-04       1485.60
4       Paulo Santos  Camisa Masculina Festa Balada 2023-01-05        876.84
5    Gabriel Cardoso                 Bota Masculina 2023-01-06        448.28
6   Leonardo Almeida        Jaqueta Masculina Preta 2023-01-07        602.00
7     Eliane Moreira              Bolsa de Trabalho 2023-01-08        994.92
8    Nicolas Pereira    Kit de Pinceis de Maquiagem 2023-01-09       1048.68
9     Amanda Martins               Vestido Infantil 2023-01-10         59.90
10  Leonardo Almeida                Calça Bailarina 2023-01-11        281.40
11    Eliane Moreira                 Camisa Térmica 2023-01-12         83.80
12   Nicolas Pereira                  Sapato Social 2023-01-13        573.30
13    Amanda Martins               Sapatilha Sapato 2023-01-14        503.10
14    Eliane Moreira                 Colar Pingente 2023-01-15        719.20
15      Angela Maria                 Tênis Feminino 2023-01-16        359.96
16    Carlos Moreira          Calça Feminina Jogger 2023-01-17        489.93
17    Eliane Moreira               Camisa Masculina 2023-01-18       1073.80
18   Nicolas Pereira              Bermuda Masculino 2023-01-19       1039.92
19  Leonardo Almeida  Camisa Masculina Festa Balada 2023-01-20       1315.26
20   Gabriel Cardoso                 Bota Masculina 2023-01-21       1344.84
21  Leonardo Almeida        Jaqueta Masculina Preta 2023-01-22        903.00
22    Eliane Moreira              Bolsa de Trabalho 2023-01-23        994.92
23   Nicolas Pereira    Kit de Pinceis de Maquiagem 2023-01-24       1048.68
24    Amanda Martins               Vestido Infantil 2023-01-25        479.20
25    Eliane Moreira                Calça Bailarina 2023-01-26        234.50
26   Nicolas Pereira                 Camisa Térmica 2023-01-27        377.10
27    Amanda Martins                  Sapato Social 2023-01-28        737.10

In [31]:
import pandas as pd; 

#caminhoWindows = "C:/Users/NSOUZA/OneDrive - Daimler Truck/04-CURSOS/23-Analise_dadosRPA/Vendas_Jan.xlsx"
caminhoLinux = "/home/nsouza/Público/Cursos/analisedadosRPA/Vendas_Jan.xlsx"
vendas_DataFrame = pd.read_excel(caminhoLinux)
display(vendas_DataFrame.columns)

Index(['Vendedor', 'Produto', 'Data Venda', 'Total Vendas'], dtype='str')

In [32]:
import pandas as pd; 
#caminhoWindows = "C:/Users/NSOUZA/OneDrive - Daimler Truck/04-CURSOS/23-Analise_dadosRPA/Vendas_Jan.xlsx"
caminhoLinux = "/home/nsouza/Público/Cursos/analisedadosRPA/Vendas_Jan.xlsx"
vendas_DataFrame = pd.read_excel(caminhoLinux)

#Informa as colunas existentes no DataFrame
display(vendas_DataFrame.columns)

Index(['Vendedor', 'Produto', 'Data Venda', 'Total Vendas'], dtype='str')

In [37]:
import pandas as pd; 

#caminhoWindows = "C:/Users/NSOUZA/OneDrive - Daimler Truck/04-CURSOS/23-Analise_dadosRPA/Vendas_Jan.xlsx"
caminhoLinux = "/home/nsouza/Público/Cursos/analisedadosRPA/Vendas_Jan.xlsx"
vendas_DataFrame = pd.read_excel(caminhoLinux)


#Imprimir a 5 primeiras linhas do DataFrame
display(vendas_DataFrame.head())

           Vendedor                        Produto Data Venda  Total Vendas
0  Leonardo Almeida                 Tênis Feminino 2023-01-01        719.92
1    Eliane Moreira          Calça Feminina Jogger 2023-01-02        139.98
2   Nicolas Pereira               Camisa Masculina 2023-01-03        306.80
3    Amanda Martins              Bermuda Masculino 2023-01-04       1485.60
4      Paulo Santos  Camisa Masculina Festa Balada 2023-01-05        876.84

In [34]:
import pandas as pd; 

#caminhoWindows = "C:/Users/NSOUZA/OneDrive - Daimler Truck/04-CURSOS/23-Analise_dadosRPA/Vendas_Jan.xlsx"
caminhoLinux = "/home/nsouza/Público/Cursos/analisedadosRPA/Vendas_Jan.xlsx"
vendas_DataFrame = pd.read_excel(caminhoLinux)
#Exbir a coluna "Vendedor" do DataFrame
display(vendas_DataFrame["Vendedor"])

0     Leonardo Almeida
1       Eliane Moreira
2      Nicolas Pereira
3       Amanda Martins
4         Paulo Santos
5      Gabriel Cardoso
6     Leonardo Almeida
7       Eliane Moreira
8      Nicolas Pereira
9       Amanda Martins
10    Leonardo Almeida
11      Eliane Moreira
12     Nicolas Pereira
13      Amanda Martins
14      Eliane Moreira
15        Angela Maria
16      Carlos Moreira
17      Eliane Moreira
18     Nicolas Pereira
19    Leonardo Almeida
20     Gabriel Cardoso
21    Leonardo Almeida
22      Eliane Moreira
23     Nicolas Pereira
24      Amanda Martins
25      Eliane Moreira
26     Nicolas Pereira
27      Amanda Martins
Name: Vendedor, dtype: str

In [35]:
import pandas as pd; 

#caminhoWindows = "C:/Users/NSOUZA/OneDrive - Daimler Truck/04-CURSOS/23-Analise_dadosRPA/Vendas_Jan.xlsx"
caminhoLinux = "/home/nsouza/Público/Cursos/analisedadosRPA/Vendas_Jan.xlsx"
vendas_DataFrame = pd.read_excel(caminhoLinux)


#Exbir apenas lagumas colunas do DataFrame
display(vendas_DataFrame[["Vendedor","Total Vendas"]].head())

           Vendedor  Total Vendas
0  Leonardo Almeida        719.92
1    Eliane Moreira        139.98
2   Nicolas Pereira        306.80
3    Amanda Martins       1485.60
4      Paulo Santos        876.84

In [39]:
import pandas as pd; 
#caminhoWindows = "C:/Users/NSOUZA/OneDrive - Daimler Truck/04-CURSOS/23-Analise_dadosRPA/Vendas_Jan.xlsx"
caminhoLinux = "/home/nsouza/Público/Cursos/analisedadosRPA/Vendas_Jan.xlsx"
vendas_DataFrame = pd.read_excel(caminhoLinux)
#Loc limite a quantidade de linhas
display(vendas_DataFrame.loc[1:10])

            Vendedor                        Produto Data Venda  Total Vendas
1     Eliane Moreira          Calça Feminina Jogger 2023-01-02        139.98
2    Nicolas Pereira               Camisa Masculina 2023-01-03        306.80
3     Amanda Martins              Bermuda Masculino 2023-01-04       1485.60
4       Paulo Santos  Camisa Masculina Festa Balada 2023-01-05        876.84
5    Gabriel Cardoso                 Bota Masculina 2023-01-06        448.28
6   Leonardo Almeida        Jaqueta Masculina Preta 2023-01-07        602.00
7     Eliane Moreira              Bolsa de Trabalho 2023-01-08        994.92
8    Nicolas Pereira    Kit de Pinceis de Maquiagem 2023-01-09       1048.68
9     Amanda Martins               Vestido Infantil 2023-01-10         59.90
10  Leonardo Almeida                Calça Bailarina 2023-01-11        281.40