In [1]:
import pandas as opcoesPanda

notasAluno_DataFrame = opcoesPanda.DataFrame({
    "Nome": ["João", "Maria", "Pedro", "Ana"],
    "Nota1": [7.5, 8.0, 6.0, 9.0],   
    "Nota2": [8.0, 7.5, 8.5, 8.0],
    "Nota3": [9.0, 8.5, 7.0, 8.5],
    "Nota4": [7.0, 8.0, 6.5, 9.0]
})

display(notasAluno_DataFrame)

    Nome  Nota1  Nota2  Nota3  Nota4
0   João    7.5    8.0    9.0    7.0
1  Maria    8.0    7.5    8.5    8.0
2  Pedro    6.0    8.5    7.0    6.5
3    Ana    9.0    8.0    8.5    9.0

In [15]:
# Adicionando colunas
notasAluno_DataFrame["Média"] = (notasAluno_DataFrame[["Nota1", "Nota2", "Nota3", "Nota4"]].mean(axis=1))

#Criando valor padrão
notasAluno_DataFrame["Faltas"] = 5

#Localizando e alterando a note do Pedro
notasAluno_DataFrame.loc[2, "Nota2"] = 50

display(notasAluno_DataFrame)

    Nome  Nota1  Nota2  Nota3  Nota4  Média  Faltas
0   João    7.5    8.0    9.0    7.0  7.875       5
1  Maria    8.0    7.5    8.5    8.0  8.000       5
2  Pedro    6.0   50.0    7.0    6.5  7.000       5
3    Ana    9.0    8.0    8.5    9.0  8.625       5